nome = str(input('Digite seu nome completo: '))
print('=-'*40)
print('-> seu nome em maiúsculo: {}'.format((nome.upper())))
print('=-'*40)
print('-> seu nome em minusculo: {}'.format((nome.lower())))
print('=-'*40)
nome_sem_espaços = nome.replace(' ', '')
print('-> seu nome tem {} letras ao todo.'.format((len(nome_sem_espaços))))
print('=-'*40)
dividido = nome.split()
print('-> seu primeiro nome tem {} letras.'.format((len(dividido[0]))))
print('=-'*40)